<x-app-layout title="Dashboard">
    <section class="inventra-kpi-grid">
        <article class="inventra-kpi"><span class="inventra-kpi-icon">▣</span><p>{{ $inventoryValue === null ? 'Products Available' : 'Total Inventory Value' }}</p><strong>{{ $inventoryValue === null ? \App\Models\Product::query()->active()->count() : '₦'.\App\Support\Money::format($inventoryValue) }}</strong></article>
        <article class="inventra-kpi"><span class="inventra-kpi-icon is-green">▤</span><p>Sales Today</p><strong>₦{{ \App\Support\Money::format($salesToday) }}</strong></article>
        <article class="inventra-kpi"><span class="inventra-kpi-icon is-amber">△</span><p>Low-Stock Products</p><strong>{{ $lowStockCount }}</strong></article>
        <article class="inventra-kpi"><span class="inventra-kpi-icon is-muted">◷</span><p>Pending Follow-Ups</p><strong>0</strong></article>
    </section>
    <section class="inventra-dashboard-split">
        <article class="inventra-panel inventra-dashboard-main">@if($recentSales->isEmpty())<div class="inventra-empty"><span>▥</span><h2>No sales yet</h2><p>Record your first sale to see your dashboard come to life.</p><a href="{{ route('sales.create') }}" class="inventra-primary-action"><img src="{{ asset('images/figma/icon-plus.svg') }}" alt="">Record Sale</a></div>@else<div class="inventra-panel-head"><h2>Sales overview</h2><a href="{{ route('sales.index') }}">View all</a></div><div class="inventra-mini-chart">@foreach([48,62,54,78,69,92] as $height)<i style="--bar-height: {{ $height }}%"></i>@endforeach</div>@endif</article>
        <article class="inventra-panel"><div class="inventra-panel-head"><h2>Low on stock</h2><a href="{{ route('inventory.index', ['stock' => 'low']) }}">View all</a></div>@if($lowStockProducts->isEmpty())<div class="inventra-empty is-compact"><span>◇</span><h2>Your inventory is empty</h2><p>Add your first product to start tracking stock.</p>@can('create', \App\Models\Product::class)<a href="{{ route('inventory.products.create') }}" class="inventra-primary-action"><img src="{{ asset('images/figma/icon-plus.svg') }}" alt="">Add Product</a>@endcan</div>@else<ul class="inventra-low-stock">@foreach($lowStockProducts as $product)<li><span><b>{{ $product->name }}</b><small>{{ $product->sku }}</small></span><strong>{{ $product->current_stock }} {{ $product->unit->value }}</strong></li>@endforeach</ul>@endif</article>
    </section>
    <section class="inventra-panel inventra-recent-sales"><div class="inventra-panel-head"><h2>Recent sales</h2><a href="{{ route('sales.index') }}">View all</a></div><div class="overflow-x-auto"><table class="inventra-table"><thead><tr><th>Date</th><th>Customer</th><th>Items</th><th class="text-right">Amount</th><th>Status</th><th></th></tr></thead><tbody>@forelse($recentSales as $sale)<tr><td>{{ $sale->created_at->format('d M, Y') }}</td><td><b>{{ $sale->customer_name_snapshot }}</b><small>{{ $sale->sale_number }}</small></td><td>{{ $sale->items_count }}</td><td class="text-right">₦{{ \App\Support\Money::format($sale->total_amount) }}</td><td><span class="inventra-pill inventra-pill-{{ $sale->payment_status->value }}">{{ ucfirst($sale->payment_status->value) }}</span></td><td><a href="{{ route('sales.show', $sale) }}">•••</a></td></tr>@empty<tr><td colspan="6"><div class="inventra-empty is-table"><span>▥</span><h2>No sales recorded yet</h2><p>Your sales history will show up here.</p><a href="{{ route('sales.create') }}" class="inventra-primary-action"><img src="{{ asset('images/figma/icon-plus.svg') }}" alt="">Record Sale</a></div></td></tr>@endforelse</tbody></table></div></section>
</x-app-layout>
