<?php

namespace App\Actions\Settings;

use App\Models\BusinessSetting;
use App\Models\User;
use App\Services\AuditLogger;
use App\Settings\BusinessSettings;
use App\Support\ImageStore;
use App\Tenancy\CurrentBusiness;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\DB;
use Throwable;

/**
 * Attaches, replaces or removes the business logo.
 *
 * The path change and its audit row commit together or not at all. The filesystem cannot join that
 * transaction, so the order around it is what keeps the two in step: the new file is written before
 * the transaction, so the row never points at a file that failed to persist; a failed transaction
 * deletes only that new file, so the logo in use survives; and the file being replaced is deleted
 * only after commit, so nothing valid is discarded early. The previous path is read under the row
 * lock, so two concurrent changes cannot each delete a file the other still references.
 *
 * The path is generated by ImageStore from the file's real decoded type; nothing the browser sent
 * names it.
 */
class SetBusinessLogo
{
    public function __construct(
        private readonly ImageStore $images,
        private readonly AuditLogger $audit,
        private readonly BusinessSettings $settings,
        private readonly CurrentBusiness $currentBusiness,
    ) {}

    public function store(User $actor, UploadedFile $file): BusinessSetting
    {
        $business = $this->currentBusiness->forActor($actor);
        $path = $this->images->put($file, ImageStore::BUSINESS);

        try {
            $previous = DB::transaction(function () use ($business, $path, $actor): ?string {
                $locked = BusinessSetting::query()
                    ->forBusiness($business)
                    ->lockForUpdate()
                    ->firstOrFail();
                $previous = $locked->logo_path;

                $locked->forceFill(['logo_path' => $path, 'updated_by' => $actor->id])->save();

                $this->audit->record(
                    $previous === null ? 'business_logo_attached' : 'business_logo_replaced',
                    $locked,
                    $actor,
                    oldValues: ['logo_path' => $previous],
                    newValues: ['logo_path' => $path],
                    explicitDiff: true,
                );

                return $previous;
            });
        } catch (Throwable $exception) {
            // Nothing committed, so the only file to discard is the one written for this attempt.
            $this->images->delete($path);

            throw $exception;
        }

        if ($previous !== null && $previous !== $path) {
            $this->images->delete($previous);
        }

        $this->settings->forget();

        return $this->settings->for($business);
    }

    public function remove(User $actor): BusinessSetting
    {
        $business = $this->currentBusiness->forActor($actor);

        $previous = DB::transaction(function () use ($actor, $business): ?string {
            $locked = BusinessSetting::query()
                ->forBusiness($business)
                ->lockForUpdate()
                ->firstOrFail();
            $previous = $locked->logo_path;

            if ($previous === null) {
                return null;
            }

            $locked->forceFill(['logo_path' => null, 'updated_by' => $actor->id])->save();

            $this->audit->record('business_logo_removed', $locked, $actor,
                oldValues: ['logo_path' => $previous], newValues: ['logo_path' => null], explicitDiff: true);

            return $previous;
        });

        if ($previous === null) {
            return $this->settings->for($business);
        }

        // Only once the row no longer references it.
        $this->images->delete($previous);
        $this->settings->forget();

        return $this->settings->for($business);
    }
}
