<x-app-layout :title="'WhatsApp attempt '.$delivery->attempt">
    <x-validation-errors />
    <a href="{{ auth()->user()->can('viewAny', \App\Models\WhatsAppDelivery::class) ? route('whatsapp.deliveries.index') : route('sales.show', $delivery->sale) }}" class="text-sm font-semibold text-[#0b56c9]">← {{ auth()->user()->can('viewAny', \App\Models\WhatsAppDelivery::class) ? 'Delivery logs' : 'Sale' }}</a><h1 class="mt-3 text-3xl font-bold">Receipt delivery attempt {{ $delivery->attempt }}</h1>
    <dl class="mt-6 grid gap-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:grid-cols-2">@foreach(['Sale' => $delivery->sale->sale_number, 'Customer' => $delivery->customer->customer_code.' · '.$delivery->customer->full_name, 'Destination used' => $delivery->destination_phone, 'Status' => ucfirst($delivery->status->value), 'Attempt' => $delivery->attempt, 'Requested by' => $delivery->creator->name, 'Consent checked' => $delivery->consent_checked_at->format('M j, Y g:i A'), 'Consent granted' => $delivery->consent_opt_in_at_snapshot?->format('M j, Y g:i A') ?? '—', 'Requested' => $delivery->requested_at->format('M j, Y g:i A'), 'Provider message ID' => $delivery->provider_message_id ?? 'Not obtained'] as $label => $value)<div><dt class="text-xs uppercase text-slate-500">{{ $label }}</dt><dd class="mt-1 font-semibold">{{ $value }}</dd></div>@endforeach</dl>
    @if($delivery->failure_code === 'outcome_unknown' && $delivery->status === \App\Enums\WhatsAppDeliveryStatus::Pending)<div class="mt-5 rounded-xl bg-amber-50 p-4 text-amber-900"><p class="font-bold">Outcome could not be confirmed.</p><p class="mt-1 text-sm">Inventra did not receive a provider message ID, so webhook reconciliation is impossible. Do not retry automatically.</p></div>@endif
    @if($delivery->failure_reason)<p class="mt-5 rounded-xl bg-red-50 p-4 text-red-800">{{ $delivery->failure_code }} · {{ $delivery->failure_reason }}</p>@endif
    @if($delivery->status === \App\Enums\WhatsAppDeliveryStatus::Unresolved)<div class="mt-5 rounded-xl border border-slate-200 bg-slate-50 p-4"><p class="font-bold">Manually marked unresolved</p><p class="mt-1 text-sm text-slate-700">{{ $delivery->resolution_note }}</p><p class="mt-2 text-xs text-slate-500">Resolved by {{ $delivery->resolver->name }} on {{ $delivery->resolved_at->format('M j, Y g:i A') }}</p></div>@endif
    @can('resolveUnknown', $delivery)<form method="POST" action="{{ route('whatsapp.deliveries.resolve-unknown', $delivery) }}" class="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4">@csrf<label for="resolution_note" class="font-semibold text-amber-950">Resolution note</label><p class="mt-1 text-sm text-amber-900">Mark this attempt unresolved only after manual investigation. It will remain non-retryable.</p><textarea id="resolution_note" name="resolution_note" required minlength="10" maxlength="500" class="mt-3 w-full rounded-lg border border-amber-300 bg-white p-3">{{ \App\Support\OldInput::scalar('resolution_note') }}</textarea>@error('resolution_note')<p class="mt-1 text-sm text-red-700">{{ $message }}</p>@enderror<button class="mt-3 rounded-xl bg-amber-700 px-5 py-3 font-semibold text-white" onclick="return confirm('Mark this ambiguous attempt unresolved? It will not become retryable.')">Mark as unresolved</button></form>@endcan
    @can('retry', $delivery)<div class="mt-5"><p class="mb-3 text-sm font-semibold text-amber-800">The previous send definitively failed. A retry creates a new delivery attempt.</p><form method="POST" action="{{ route('sales.whatsapp.retry', [$delivery->sale, $delivery]) }}" onsubmit="return confirm('Create a new delivery attempt after rechecking current consent?')">@csrf<input type="hidden" name="request_token" value="{{ $retryToken }}"><button class="rounded-xl bg-emerald-600 px-5 py-3 font-semibold text-white">Retry with current consent</button></form></div>@endcan
</x-app-layout>
