<x-app-layout title="Staff accounts">
    <div class="flex flex-wrap items-end justify-between gap-4">
        <div><p class="text-sm font-semibold uppercase tracking-[0.18em] text-[#0b56c9]">Administration</p><h1 class="mt-2 text-3xl font-bold">Staff accounts</h1><p class="mt-2 text-slate-600">Manage access, account state, and staff security activity.</p></div>
        <a href="{{ route('staff.create') }}" class="rounded-xl bg-[#0b56c9] px-5 py-3 font-semibold text-white shadow-sm hover:bg-[#0848aa]">Add staff</a>
    </div>
    <form method="GET" class="ui-filter-bar mt-7 grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:grid-cols-4">
        <input aria-label="Search records" name="search" value="{{ is_string(request('search')) ? request('search') : '' }}" placeholder="Name, email, or phone" class="rounded-xl border border-slate-300 px-4 py-2.5 outline-none focus:border-[#0b56c9] focus:ring-4 focus:ring-blue-100">
        <select aria-label="Role" name="role" class="rounded-xl border border-slate-300 px-4 py-2.5"><option value="">All roles</option>@foreach (\App\Enums\UserRole::cases() as $role)<option value="{{ $role->value }}" @selected(request('role') === $role->value)>{{ $role->label() }}</option>@endforeach</select>
        <select aria-label="Status" name="status" class="rounded-xl border border-slate-300 px-4 py-2.5"><option value="">All statuses</option>@foreach (\App\Enums\UserStatus::cases() as $status)<option value="{{ $status->value }}" @selected(request('status') === $status->value)>{{ ucfirst($status->value) }}</option>@endforeach</select>
        <button class="rounded-xl bg-slate-900 px-4 py-2.5 font-semibold text-white">Apply filters</button>
    </form>
<div class="mt-2 text-right"><x-filter-reset /></div>
    <div class="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-left text-sm">
        <thead class="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th class="ui-sn">S/N</th><x-sort-header key="name" label="Staff name" :active="$sort['key']" :direction="$sort['direction']" /><x-sort-header key="email" label="Email address" :active="$sort['key']" :direction="$sort['direction']" /><x-sort-header key="phone" label="Phone" :active="$sort['key']" :direction="$sort['direction']" /><x-sort-header key="role" label="Role" :active="$sort['key']" :direction="$sort['direction']" /><x-sort-header key="status" label="Status" :active="$sort['key']" :direction="$sort['direction']" /><x-sort-header key="last_login" label="Last login" :active="$sort['key']" :direction="$sort['direction']" /><th class="px-5 py-4"><span class="sr-only">Actions</span></th></tr></thead>
        <tbody class="divide-y divide-slate-100">@forelse ($staff as $staffMember)<tr class="hover:bg-slate-50"><td class="ui-sn">{{ $staff->firstItem() + $loop->index }}</td><td class="px-5 py-4 font-semibold">{{ $staffMember->name }}</td><td class="px-5 py-4 text-slate-600">{{ $staffMember->email }}</td><td class="px-5 py-4 text-slate-600">{{ $staffMember->phone ?: '—' }}</td><td class="px-5 py-4">{{ $staffMember->role->label() }}</td><td class="px-5 py-4"><x-status-badge :status="$staffMember->status" /></td><td class="px-5 py-4 text-slate-600">{{ $staffMember->last_login_at?->diffForHumans() ?? 'Never' }}</td><td class="px-5 py-4 text-right"><a href="{{ route('staff.show', $staffMember) }}" class="font-semibold text-[#0b56c9]">View</a></td></tr>@empty<tr><td colspan="8" class="px-6 py-16 text-center text-slate-500"><x-empty-state title="No staff accounts match these filters." description="Try another search or adjust your filters." /></td></tr>@endforelse</tbody>
    </table></div><x-table-footer :paginator="$staff" noun="staff account" /></div>
</x-app-layout>
