<x-app-layout :title="$title"><div class="flex items-start justify-between"><div><a class="text-blue-700" href="{{ route('reports.index') }}">← Reports</a><h2 class="mt-2 text-2xl font-bold">{{ $title }}</h2>@if($type === 'receivables')<p class="text-slate-500">All current outstanding completed Sales · not a historical period-end reconstruction</p>@else<p class="text-slate-500">{{ $filters->from }} through {{ $filters->to }} inclusive · {{ config('business.timezone') }}</p>@endif</div></div>
@if(in_array($type, ['customers', 'staff'], true))<p class="mt-4 text-sm text-slate-600">Includes completed Sales made in this period and payments collected in this period against completed Sales, including older Sales. Voided Sales are excluded. Names are current profile names; grouping uses permanent record IDs. Outstanding is the current balance of Sales made in this period, not all customer receivables.</p>@endif
<form method="GET" class="mt-6 grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-4">@if($type !== 'receivables')<label class="text-sm">From<input class="mt-1 w-full rounded-xl border-slate-300" type="date" name="from" value="{{ $filters->from }}"></label><label class="text-sm">To<input class="mt-1 w-full rounded-xl border-slate-300" type="date" name="to" value="{{ $filters->to }}"></label>@endif
@if(in_array($type,['sales','collections','receivables','expenses','purchases','staff']))<label class="text-sm">Staff<select class="mt-1 w-full rounded-xl border-slate-300" name="staff"><option value="">All staff</option>@foreach($staffOptions as $staff)<option value="{{ $staff->id }}" @selected($filters->staff == $staff->id)>{{ $staff->name }}</option>@endforeach</select></label>@endif
@if(in_array($type,['sales','collections','receivables','customers']))<label class="text-sm">Customer<select class="mt-1 w-full rounded-xl border-slate-300" name="customer"><option value="">All customers</option>@foreach($customerOptions as $customer)<option value="{{ $customer->id }}" @selected($filters->customer == $customer->id)>{{ $customer->customer_code }} · {{ $customer->full_name }}</option>@endforeach</select></label>@endif
@if(in_array($type,['inventory','products']))<label class="text-sm">Product<select class="mt-1 w-full rounded-xl border-slate-300" name="product"><option value="">All products</option>@foreach($productOptions as $product)<option value="{{ $product->id }}" @selected($filters->product == $product->id)>{{ $product->sku }} · {{ $product->name }}</option>@endforeach</select></label>@endif
@if($type==='expenses')<label class="text-sm">Category<select class="mt-1 w-full rounded-xl border-slate-300" name="category"><option value="">All categories</option>@foreach($categoryOptions as $category)<option value="{{ $category->id }}" @selected($filters->category == $category->id)>{{ $category->name }}</option>@endforeach</select></label>@endif
@if($type==='purchases')<label class="text-sm">Supplier<select class="mt-1 w-full rounded-xl border-slate-300" name="supplier"><option value="">All suppliers</option>@foreach($supplierOptions as $supplier)<option value="{{ $supplier->id }}" @selected($filters->supplier == $supplier->id)>{{ $supplier->supplier_code }} · {{ $supplier->name }}</option>@endforeach</select></label>@endif
@if(in_array($type,['collections','expenses']))<label class="text-sm">Payment method<select class="mt-1 w-full rounded-xl border-slate-300" name="payment_method"><option value="">All methods</option>@foreach(\App\Enums\PaymentMethod::cases() as $method)<option value="{{ $method->value }}" @selected($filters->paymentMethod === $method->value)>{{ $method->label() }}</option>@endforeach</select></label>@endif<button class="self-end rounded-xl bg-slate-800 px-4 py-3 text-white">Apply</button></form>
@error('from')<p class="mt-2 text-red-700">{{ $message }}</p>@enderror
@if($integrityWarning)<p class="mt-4 rounded-xl bg-red-50 p-4 text-red-800">{{ $integrityWarning }}</p>@endif
@if(in_array($type, ['collections', 'summary'], true))<p class="mt-4 rounded-xl bg-blue-50 p-4 text-sm text-blue-900">Collections reflect the historical customer payment ledger, including payments on Sales later voided. Customer refunds are reported separately and do not rewrite received-payment history.</p>@endif
<div class="mt-6 grid gap-4 md:grid-cols-3">@foreach($metrics as $metric)<div class="rounded-2xl border bg-white p-5"><small class="text-slate-500">{{ $metric['label'] }}</small><strong class="mt-1 block text-2xl">@if($metric['format']==='money')₦{{ \App\Support\Money::format((string)$metric['value']) }}@else{{ $metric['value'] }}@endif</strong></div>@endforeach</div>
@foreach($breakdowns as $label => $items)<div class="mt-6 rounded-2xl border bg-white p-5"><h3 class="font-bold">{{ $label }}</h3>@forelse($items as $item)<div class="mt-2 flex justify-between"><span>{{ $item->label }}</span><span>@if(($item->format ?? 'money') === 'money')₦{{ \App\Support\Money::format((string)$item->value) }}@else{{ $item->value }}@endif</span></div>@empty<p class="mt-2 text-slate-500">No data.</p>@endforelse</div>@endforeach
@if($rows)<div class="mt-6 overflow-x-auto rounded-2xl border bg-white"><table class="w-full text-left text-sm"><tbody>
@forelse($rows as $row)<tr class="border-b align-top">
@if($type==='sales')<td class="p-4"><a class="text-blue-700" href="{{ route('sales.show',$row) }}">{{ $row->sale_number }}</a><br>{{ $row->created_at->timezone(config('business.timezone'))->format('d M Y') }}</td><td class="p-4">{{ $row->customer_name_snapshot }}</td><td class="p-4">{{ $row->sold_by_name_snapshot }}</td><td class="p-4">Total ₦{{ \App\Support\Money::format($row->total_amount) }}<br>Paid ₦{{ \App\Support\Money::format($row->amount_paid) }} · Due ₦{{ \App\Support\Money::format($row->balance_due) }}<br>{{ $row->payment_method->label() }} · {{ $row->payment_status->value }} · {{ $row->status->value }}</td>
@elseif($type==='collections')<td class="p-4">{{ $row->payment_number }}<br>{{ $row->paid_at->timezone(config('business.timezone'))->format('d M Y H:i') }}</td><td class="p-4">{{ $row->sale->sale_number }} · {{ $row->sale->customer_name_snapshot }}</td><td class="p-4">{{ $row->recorded_by_name_snapshot }}</td><td class="p-4">{{ $row->payment_method->label() }} · ₦{{ \App\Support\Money::format($row->amount) }}</td>
@elseif($type==='receivables')<td class="p-4">{{ $row->sale_number }}<br>{{ $row->customer_name_snapshot }}</td><td class="p-4">{{ $row->sold_by_name_snapshot }}</td><td class="p-4">Total ₦{{ \App\Support\Money::format($row->total_amount) }}<br>Paid ₦{{ \App\Support\Money::format($row->amount_paid) }}</td><td class="p-4">Due ₦{{ \App\Support\Money::format($row->balance_due) }} · {{ $row->payment_status->value }}</td>
@elseif($type==='expenses')<td class="p-4"><a class="text-blue-700" href="{{ route('expenses.show',$row) }}">{{ $row->expense_number }}</a><br>{{ $row->incurred_at->format('d M Y') }}</td><td class="p-4">{{ $row->category_name_snapshot }}</td><td class="p-4">{{ $row->description }}<br>{{ $row->recorded_by_name_snapshot }}</td><td class="p-4">{{ $row->payment_method->label() }} · ₦{{ \App\Support\Money::format($row->amount) }}</td>
@elseif($type==='purchases')<td class="p-4"><a class="text-blue-700" href="{{ route('purchases.show',$row) }}">{{ $row->purchase_number }}</a><br>{{ $row->received_at->timezone(config('business.timezone'))->format('d M Y') }}</td><td class="p-4">{{ $row->supplier_name_snapshot }}</td><td class="p-4">{{ $row->received_by_name_snapshot }} · {{ $row->items_count }} items</td><td class="p-4">₦{{ \App\Support\Money::format($row->total_amount) }}</td>
@elseif($type==='inventory')<td class="p-4">{{ $row->created_at->timezone(config('business.timezone'))->format('d M Y H:i') }}</td><td class="p-4">{{ $row->product?->sku }} · {{ $row->product?->name }}</td><td class="p-4">{{ $row->type->value }}</td><td class="p-4">{{ $row->quantity_change }}</td>
@elseif($type==='products')<td class="p-4"><span class="text-xs text-slate-500">Historical Product Snapshot</span><br>{{ $row->product_sku_snapshot }} · {{ $row->product_name_snapshot }}</td><td class="p-4">{{ $row->quantity_sold }} sold</td><td class="p-4">{{ $row->transaction_count }} transactions<br><span class="text-slate-500">Current stock — same live product: {{ $row->current_stock }}</span></td><td class="p-4">₦{{ \App\Support\Money::format((string)$row->sales_value) }}</td>
@elseif($type==='customers')<td class="p-4">{{ $row->customer_code }} · {{ $row->full_name }}</td><td class="p-4">{{ $row->sale_count }} sales · ₦{{ \App\Support\Money::format((string)$row->sales_value) }}<br>Latest sale in period: {{ $row->latest_sale ? \Illuminate\Support\Carbon::parse($row->latest_sale)->timezone(config('business.timezone'))->format('d M Y') : 'None' }}</td><td class="p-4">Collected ₦{{ \App\Support\Money::format((string)$row->collected) }}</td><td class="p-4">Outstanding ₦{{ \App\Support\Money::format((string)$row->outstanding) }}</td>
@elseif($type==='staff')<td class="p-4">{{ $row->name }}</td><td class="p-4">{{ $row->sale_count }} sales · ₦{{ \App\Support\Money::format((string)$row->sales_value) }}</td><td class="p-4">Seller-attributed collections ₦{{ \App\Support\Money::format((string)$row->seller_sale_collections) }}</td><td class="p-4">Outstanding ₦{{ \App\Support\Money::format((string)$row->outstanding) }}</td>@endif
</tr>@empty<tr><td class="p-8 text-center text-slate-500">0 records</td></tr>@endforelse</tbody></table></div><div class="mt-4">{{ $rows->links() }}</div>@endif
<p class="mt-8 text-xs text-slate-500">Operational reporting only. No profit, COGS, inventory valuation, tax, or formal accounting statement is calculated.</p></x-app-layout>
