<x-app-layout title="Customers">
    <div class="flex flex-wrap items-end justify-between gap-4">
        <div><p class="text-sm font-semibold text-[#0b56c9]">Customer management</p><h1 class="mt-1 text-3xl font-bold">Customers</h1><p class="mt-2 text-slate-600">Find customer contact and consent details.</p></div>
        @can('create', \App\Models\Customer::class)<a href="{{ route('customers.create') }}" class="rounded-xl bg-[#0b56c9] px-5 py-3 font-semibold text-white">Add customer</a>@endcan
    </div>
    <form method="GET" class="mt-7 grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:grid-cols-4">
        <input name="search" value="{{ is_string(request('search')) ? request('search') : '' }}" placeholder="Name, code, phone or email" class="rounded-xl border border-slate-300 px-4 py-2.5">
        @if($canManageStatus)<select name="status" class="rounded-xl border border-slate-300 px-3"><option value="">All statuses</option><option value="active" @selected(is_string(request('status')) && request('status') === 'active')>Active</option><option value="inactive" @selected(is_string(request('status')) && request('status') === 'inactive')>Inactive</option></select>@else<div></div>@endif
        <select name="whatsapp" class="rounded-xl border border-slate-300 px-3"><option value="">All WhatsApp preferences</option><option value="opted_in" @selected(is_string(request('whatsapp')) && request('whatsapp') === 'opted_in')>Opted in</option><option value="opted_out" @selected(is_string(request('whatsapp')) && request('whatsapp') === 'opted_out')>Not opted in</option></select>
        <button class="rounded-xl bg-slate-900 px-4 py-2.5 font-semibold text-white">Filter</button>
    </form>
    <div class="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th class="px-5 py-4">Customer</th><th class="px-5 py-4">Phone</th><th class="px-5 py-4">Email</th><th class="px-5 py-4">Status</th><th class="px-5 py-4">WhatsApp</th><th class="px-5 py-4">Last purchase</th><th></th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($customers as $customer)<tr><td class="px-5 py-4"><p class="font-semibold">{{ $customer->full_name }}</p><p class="font-mono text-xs text-slate-500">{{ $customer->customer_code }}</p></td><td class="px-5 py-4">{{ $customer->phone }}</td><td class="px-5 py-4">{{ $customer->email ?: '—' }}</td><td class="px-5 py-4"><span class="rounded-full px-2 py-1 text-xs font-semibold {{ $customer->is_active ? 'bg-emerald-100 text-emerald-800' : 'bg-slate-200 text-slate-700' }}">{{ $customer->is_active ? 'Active' : 'Inactive' }}</span></td><td class="px-5 py-4">{{ $customer->whatsapp_opt_in ? 'Opted in' : 'Not opted in' }}</td><td class="px-5 py-4 text-slate-500">—</td><td class="px-5 py-4"><a href="{{ route('customers.show', $customer) }}" class="font-semibold text-[#0b56c9]">View</a></td></tr>@empty<tr><td colspan="7" class="px-6 py-16 text-center text-slate-500">No customers match these filters.</td></tr>@endforelse</tbody></table></div>@if($customers->hasPages())<div class="border-t p-4">{{ $customers->links() }}</div>@endif</div>
</x-app-layout>
