<x-app-layout title="Record sale">
    <x-page-header title="Record a sale" description="Choose a customer, add products and record the payment." eyebrow="Sales">
        <a href="{{ route('sales.index') }}" class="ui-button">Back to sales</a>
    </x-page-header>
    <div class="ui-sale-guide"><div><b>1 · Select customer</b><p>Use a registered, active customer.</p></div><div><b>2 · Add products</b><p>Search without losing your sale details.</p></div><div><b>3 · Record payment</b><p>Final prices and totals are confirmed on submission.</p></div></div>
    <form data-sale-product-search aria-label="Search sale products" method="GET" action="{{ route('sales.create') }}" class="mt-7 flex gap-3"><input aria-label="Search products" name="product_search" value="{{ $productSearch }}" placeholder="Search active products by SKU or name" class="w-full rounded-xl border border-slate-300 px-4 py-3"><button disabled class="rounded-xl border border-slate-300 bg-white px-5 py-3 font-semibold">Search products</button></form>
    <p data-sale-search-status role="status" aria-live="polite" class="mt-2 text-sm"></p>
    <noscript><p>Product search requires JavaScript. Your sale can still be submitted using the displayed products.</p></noscript>
    <form data-sale-entry method="POST" action="{{ route('sales.store') }}" class="mt-5 space-y-6">@csrf
        <x-validation-errors />
        <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="font-bold">Customer</h2><select aria-label="Customer" name="customer_id" class="mt-4 w-full rounded-xl border border-slate-300 px-4 py-3" required><option value="">Select active customer</option>@foreach($customers as $customer)<option value="{{ $customer->id }}" @selected((string)\App\Support\OldInput::scalar('customer_id') === (string)$customer->id)>{{ $customer->customer_code }} · {{ $customer->full_name }} · {{ $customer->phone }}</option>@endforeach</select>@error('customer_id')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror</section>
        <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="font-bold">Products</h2><p class="mt-1 text-sm text-slate-500">Use up to eight lines. Repeated products are combined when the sale is completed.</p><div class="mt-4 space-y-3">@for($index=0;$index<8;$index++)<div class="ui-sale-line"><span aria-hidden="true">{{ str_pad((string) ($index + 1), 2, '0', STR_PAD_LEFT) }}</span><select aria-label="Product {{ $index + 1 }}" data-sale-product name="products[{{ $index }}][product_id]" class="rounded-xl border border-slate-300 px-3 py-2"><option value="">Select product</option>@foreach($products as $product)<option value="{{ $product->id }}" @selected((string)\App\Support\OldInput::scalar("products.$index.product_id") === (string)$product->id)>{{ $product->sku }} · {{ $product->name }} · ₦{{ \App\Support\Money::format($product->selling_price) }} · {{ $product->current_stock }} {{ $product->unit->value }}</option>@endforeach</select><input aria-label="Quantity for product {{ $index + 1 }}" name="products[{{ $index }}][quantity]" value="{{ \App\Support\OldInput::scalar("products.$index.quantity") }}" inputmode="decimal" placeholder="Quantity" class="rounded-xl border border-slate-300 px-3 py-2"></div>@endfor</div>@error('products')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror @error('products.*')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror</section>
        <section class="grid gap-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:grid-cols-2"><div><label class="text-sm font-semibold">Payment method</label><select aria-label="Payment method" name="payment_method" class="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3">@foreach(\App\Enums\PaymentMethod::cases() as $method)<option value="{{ $method->value }}" @selected(\App\Support\OldInput::scalar('payment_method','cash') === $method->value)>{{ $method->label() }}</option>@endforeach</select></div><x-form-field label="Amount paid (₦)" name="amount_paid" inputmode="decimal" :value="\App\Support\OldInput::scalar('amount_paid','0.00')" required /><div class="sm:col-span-2"><label class="text-sm font-semibold">Notes</label><textarea aria-label="Notes" name="notes" rows="3" class="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3">{{ \App\Support\OldInput::scalar('notes') }}</textarea></div></section>
        <button class="rounded-xl bg-[#0b56c9] px-6 py-3 font-semibold text-white">Complete sale</button>
    </form>
</x-app-layout>
