<?php

namespace App\Support;

use Illuminate\Contracts\Filesystem\Filesystem;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use RuntimeException;

/**
 * Stores uploaded images on the private local disk.
 *
 * Nothing here trusts the client. The stored filename is generated by the server, so a crafted
 * name cannot traverse directories or collide with an existing file; the extension is derived from
 * the file's real detected type rather than from the name it arrived with; and the type is checked
 * against an allowlist of raster formats, which excludes SVG because an SVG can carry script.
 *
 * Files live under storage/app/private and are never web-reachable. They are served only by an
 * authorized controller route, so `php artisan storage:link` is not required — which matters on
 * shared hosting where the public directory is the document root and symlinks are awkward.
 */
class ImageStore
{
    /** 2 MB. Large enough for a product photograph, small enough for shared hosting. */
    public const MAX_BYTES = 2097152;

    public const MAX_DIMENSION = 4000;

    /** Detected MIME type => the extension the server will use. */
    public const ALLOWED_TYPES = [
        'image/jpeg' => 'jpg',
        'image/png' => 'png',
        'image/webp' => 'webp',
    ];

    /** Directory (relative to the disk root) for product photographs. */
    public const PRODUCTS = 'product-images';

    /** Directory (relative to the disk root) for staff profile photographs. */
    public const STAFF = 'staff-photos';

    /**
     * The one set of upload rules every image field uses, so a product photo and a profile photo
     * can never drift into accepting different things. Only the presence requirement varies: an
     * image supplied while creating a product is optional, but everything about what is accepted —
     * type, size and dimensions — stays identical.
     *
     * @return array<int, string>
     */
    public static function validationRules(bool $required = true): array
    {
        return [
            $required ? 'required' : 'nullable',
            'file',
            // `image` and `dimensions` decode the file rather than trusting its name; put() then
            // re-reads the decoded type once more before anything is written to disk.
            'image',
            'mimes:'.implode(',', array_unique(array_merge(['jpeg'], array_values(self::ALLOWED_TYPES)))),
            'max:'.(int) (self::MAX_BYTES / 1024),
            'dimensions:max_width='.self::MAX_DIMENSION.',max_height='.self::MAX_DIMENSION,
        ];
    }

    /** @return array<string, string> */
    public static function validationMessages(string $attribute): array
    {
        return [
            $attribute.'.max' => 'The image may not be larger than 2 MB.',
            $attribute.'.mimes' => 'The image must be a JPG, PNG or WebP file.',
            $attribute.'.dimensions' => 'The image may not exceed '.self::MAX_DIMENSION.'×'.self::MAX_DIMENSION.' pixels.',
        ];
    }

    public function disk(): Filesystem
    {
        return Storage::disk('local');
    }

    /**
     * Validates and stores one upload, returning the disk-relative path to record.
     *
     * @param  self::PRODUCTS|self::STAFF  $directory
     */
    public function put(UploadedFile $file, string $directory): string
    {
        $this->assertKnownDirectory($directory);

        $type = $this->detectType($file->getRealPath());
        $extension = self::ALLOWED_TYPES[$type];
        $path = $directory.'/'.Str::random(40).'.'.$extension;

        if (! $this->disk()->put($path, file_get_contents($file->getRealPath()))) {
            throw new RuntimeException('The image could not be stored.');
        }

        return $path;
    }

    /**
     * Removes a stored image. Silently ignores a path that is already gone, and refuses any path
     * that does not have the exact shape this class generates — so a corrupted or tampered database
     * value can never delete something else.
     */
    public function delete(?string $path): void
    {
        if ($path === null || ! $this->isManagedPath($path)) {
            return;
        }

        $this->disk()->delete($path);
    }

    /** True when the path looks exactly like one `put()` produced and the file is present. */
    public function exists(?string $path): bool
    {
        return $path !== null && $this->isManagedPath($path) && $this->disk()->exists($path);
    }

    /** Absolute filesystem path, for streaming a response. */
    public function absolutePath(string $path): string
    {
        if (! $this->isManagedPath($path)) {
            throw new RuntimeException('Refusing to resolve an unmanaged image path.');
        }

        return $this->disk()->path($path);
    }

    /** The stored file's real detected type, re-read from disk rather than remembered. */
    public function typeOf(string $path): string
    {
        return $this->detectType($this->absolutePath($path));
    }

    /**
     * A path is managed only if it is one of our two directories followed by a 40-character
     * random basename and an allowed extension. No separators, dots or traversal can survive this.
     */
    private function isManagedPath(string $path): bool
    {
        $extensions = implode('|', array_unique(array_values(self::ALLOWED_TYPES)));
        $directories = implode('|', [preg_quote(self::PRODUCTS, '/'), preg_quote(self::STAFF, '/')]);

        return preg_match('/^('.$directories.')\/[A-Za-z0-9]{40}\.('.$extensions.')$/D', $path) === 1;
    }

    private function assertKnownDirectory(string $directory): void
    {
        if (! in_array($directory, [self::PRODUCTS, self::STAFF], true)) {
            throw new RuntimeException('Unknown image directory.');
        }
    }

    /**
     * Reads the file's actual content to decide what it is, and confirms it really is a decodable
     * image of a sane size. A file renamed to .png proves nothing; this does.
     */
    private function detectType(string $absolutePath): string
    {
        $size = @getimagesize($absolutePath);

        if ($size === false || ! isset($size['mime'])) {
            throw new RuntimeException('The file is not a readable image.');
        }

        $type = strtolower((string) $size['mime']);

        if (! array_key_exists($type, self::ALLOWED_TYPES)) {
            throw new RuntimeException('The image type is not supported.');
        }

        if ($size[0] < 1 || $size[1] < 1 || $size[0] > self::MAX_DIMENSION || $size[1] > self::MAX_DIMENSION) {
            throw new RuntimeException('The image dimensions are out of range.');
        }

        return $type;
    }
}
